brew "cowsay"
brew "exa"
brew "htop"
brew "jq"
brew "mas"
brew "mkcert"
brew "neovim"
brew "onyx"
brew "openssl@1.1"
brew "the_silver_searcher"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "alfred"
cask "background-music"
cask "docker"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "slack"
cask "spectacle"
cask "spotify"
cask "tableplus"
cask "visual-studio-code"
cask "vlc"
cask "notion"

mas "Monosnap", id: 540348655
